#!/usr/bin/env bash
# GENERATED by release-export -- do not edit by hand.
set -euo pipefail

MODULE="github.com/agent-in-the-shell/agent-in-the-shell"
REPO="agent-in-the-shell/agent-in-the-shell"
SERVICES=(
  "agent-model"
)

usage() {
  cat >&2 <<'USAGE'
usage: release-smoke.sh <archives|go-install|homebrew|docker> --tag <tag> [--platform <os/arch>]
USAGE
  exit 2
}

retry() {
  local attempts="${RETRY_ATTEMPTS:-8}"
  local delay="${RETRY_DELAY:-10}"
  local n=1
  local status=0
  until "$@"; do
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      return "$status"
    fi
    echo "retry $n/$attempts failed: $*" >&2
    sleep "$delay"
    n=$((n + 1))
  done
}

default_platform() {
  local os arch
  case "$(uname -s)" in
    Linux) os=linux ;;
    Darwin) os=darwin ;;
    *) echo "unsupported OS: $(uname -s)" >&2; exit 2 ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) echo "unsupported arch: $(uname -m)" >&2; exit 2 ;;
  esac
  printf '%s/%s\n' "$os" "$arch"
}

split_platform() {
  local platform="$1"
  GOOS="${platform%/*}"
  GOARCH="${platform#*/}"
  if [ "$GOOS" = "$GOARCH" ] || [ -z "$GOOS" ] || [ -z "$GOARCH" ]; then
    echo "invalid platform: $platform" >&2
    exit 2
  fi
}

smoke_args_for() {
  local service="$1"
  SMOKE_ARGS=("--help")
  case "$service" in
    agent-model)
      SMOKE_ARGS=("schema")
      ;;
  esac
}

run_binary_smoke() {
  local bin="$1"
  local service="$2"
  local work="$3"
  mkdir -p "$work"
  case "$service" in
    agent-task)
      "$bin" --config "$work/config.toml" --db "$work/tasks.db" task create --title "release smoke" --quiet
      "$bin" --config "$work/config.toml" --db "$work/tasks.db" task list | grep -q "release smoke"
      ;;
    *)
      smoke_args_for "$service"
      "$bin" "${SMOKE_ARGS[@]}"
      ;;
  esac
}

run_archives() {
  split_platform "$PLATFORM"
  local root
  root="$(mktemp -d)"
  for service in "${SERVICES[@]}"; do
    local asset archive extract_dir bin
    asset="${service}_${GOOS}_${GOARCH}.tar.gz"
    archive="$root/$asset"
    extract_dir="$root/$service"
    mkdir -p "$extract_dir"
    retry curl -fsSL -o "$archive" "https://github.com/$REPO/releases/download/$TAG/$asset"
    tar -xzf "$archive" -C "$extract_dir"
    bin="$extract_dir/$service"
    if [ ! -x "$bin" ]; then
      chmod +x "$bin"
    fi
    run_binary_smoke "$bin" "$service" "$root/smoke-$service"
  done
}

run_go_install() {
  local root
  root="$(mktemp -d)"
  export GOBIN="$root/bin"
  export GOMODCACHE="$root/mod"
  export GOCACHE="$root/cache"
  mkdir -p "$GOBIN" "$GOMODCACHE" "$GOCACHE"
  retry go list -m "$MODULE@$TAG" >/dev/null
  for service in "${SERVICES[@]}"; do
    retry go install "$MODULE/cmd/$service@$TAG"
    run_binary_smoke "$GOBIN/$service" "$service" "$root/smoke-$service"
  done
}

run_homebrew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is not installed on this runner" >&2
    exit 1
  fi
  local root
  root="$(mktemp -d)"
  retry brew update
  for service in "${SERVICES[@]}"; do
    retry brew install "agent-in-the-shell/tap/$service"
    local want got
    want="${TAG#v}"
    got="$(brew list --versions "$service" | awk 'NR == 1 {print $2}')"
    if [ "$got" != "$want" ] && [ "$got" != "$TAG" ]; then
      echo "Homebrew installed $service version $got, want $TAG" >&2
      exit 1
    fi
    local bin
    bin="$(command -v "$service")"
    run_binary_smoke "$bin" "$service" "$root/smoke-$service"
  done
}

run_docker() {
  split_platform "$PLATFORM"
  local image_tag="${TAG#v}"
  for service in "${SERVICES[@]}"; do
    local image inspect compact
    image="ghcr.io/agent-in-the-shell/$service:$image_tag"
    inspect="$(retry docker buildx imagetools inspect --raw "$image")"
    compact="$(printf '%s' "$inspect" | tr -d '[:space:]')"
    echo "$compact" | grep -q "\"os\":\"$GOOS\""
    echo "$compact" | grep -q "\"architecture\":\"$GOARCH\""
    retry docker pull --platform "$PLATFORM" "$image"
    smoke_args_for "$service"
    retry docker run --rm --platform "$PLATFORM" "$image" "${SMOKE_ARGS[@]}"
  done
}

main() {
  if [ "${#SERVICES[@]}" -eq 0 ]; then
    echo "no released services were generated into this smoke script" >&2
    exit 1
  fi
  if [ $# -lt 1 ]; then
    usage
  fi
  local cmd="$1"
  shift
  TAG=""
  PLATFORM="$(default_platform)"
  while [ $# -gt 0 ]; do
    case "$1" in
      --tag)
        [ $# -ge 2 ] || usage
        TAG="$2"
        shift 2
        ;;
      --platform)
        [ $# -ge 2 ] || usage
        PLATFORM="$2"
        shift 2
        ;;
      *)
        usage
        ;;
    esac
  done
  if [ -z "$TAG" ]; then
    usage
  fi
  case "$cmd" in
    archives) run_archives ;;
    go-install) run_go_install ;;
    homebrew) run_homebrew ;;
    docker) run_docker ;;
    *) usage ;;
  esac
}

main "$@"
